# Generated by Django 3.2.5 on 2021-08-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=100000)),
                ('image', models.ImageField(upload_to='images/')),
                ('publish_time', models.CharField(max_length=50)),
                ('update_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(upload_to='profile/')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
