# Generated by Django 3.2.5 on 2021-08-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile/'),
        ),
    ]
