# Generated by Django 3.2.5 on 2021-08-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_articles_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='profile_pic',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
