# Generated by Django 3.2.5 on 2021-08-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
