# Generated by Django 3.2.5 on 2021-08-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='com_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
